language: java
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_87c1d8e9dcc4_key -iv $encrypted_87c1d8e9dcc4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: "$IP"
  apt:
    packages:
    - sshpass
branches:
  only:
  - master
script: true
after_success:
- curl http://$IP:5010/clickplus
