version: '2'
services:
    clickplus-app:
        image: clickplus
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://clickplus-mysql:3306/clickplus?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://clickplus-elasticsearch:9200
        ports:
            - 8080:8080
    clickplus-mysql:
        extends:
            file: mysql.yml
            service: clickplus-mysql
    clickplus-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: clickplus-elasticsearch
